### ISSUE TITLE
Issue with updating the checksum key in asset

### ISSUE THREAD

**Issue by nandeeshb09** [sensu/sensu-go#3506]
Hey Team,

I have issue with sensu go ,where if we try to update checksum key in asset ,its not catching up and also its not creating any key folder in sensu agent.

We are using 5.12 version of sensu image.

Yesterday it was working fine, once we added a new files and updated the sha512 key, but checks are failing to update the checksum key. We are using s3 bucket to store the assets.

Here is the error .

error getting assets for event: sha512 '14937a84d523d8876d654988ce8935c89859b13cc91425ebcc23cf222a34b8d39d42165e4a4d9f1a985bc936d10725fa397005aa3701d69224d968b7dde5d346' does not match specified sha512: '04de733f1e780f5991e5f3effb29e4efa173e16dd140ece1df027b6c82ae546eddaeac4ebf970a78f63b9ced66f2f397eb8ec4ece17833f62520c6389b2f22eb'

Its generating new key every time, not sure whats happening. can you please help here.

**Comment by nandeeshb09** [comment]
we have fixed it.

**Comment by zscaler-bdonahue** [comment]
In which version was this fixed? 
I am still seeing this error on 5.17.1.
